### ISSUE TITLE
Decide on a caching mechanism for query results

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/arcticreport#1]
The two primary query functions in the package: `query_objects` and `query_version_chains` take 20 minutes and 100 minutes to run, respectively. `query_objects` returns a data.frame with a row for every object in the ADC. `query_version_chains` takes the result of `query_objects` and assigns an arbitrary series identifier to each version chain. The rest of the functionality in the package is slicing, dicing, summarizing, and plotting metrics based on those two tables.

Since the functions take so long to run, it is definitely not practical to run these two functions often. For CI, we could build a status page that runs everything once a day or so, and fills in tables for the quarterly metrics when those milestones show up. For local testing, or creating one-off kind of plots, it would be beneficial to set up a standard way of caching those query results for ease of use.

Open to any suggestions. The bigger of the two tables is about 100MB when saved to disk.

**Comment by jeanetteclark** [comment]
As a side note: we might be able to parallelize the `query_version_chains` function but I'm not sure if hitting our Solr endpoint that hard will cause issues.

**Comment by mbjones** [comment]
Related to https://github.com/NCEAS/metacat/issues/1429. There are massively faster approaches to generating this information.

**Comment by jeanetteclark** [comment]
Yeah would be great to see that closure table implemented. The way I get this info now is *painfully* slow

**Comment by jeanetteclark** [comment]
I've decided to use a fairly simple system that uses `rappdirs`.

In the two query functions the following steps are taken:

- look for cached files and determine their age
- determine whether the cache should be refreshed based on tolerance given in the function arguments
- either load the cached file (an RDS) or run the query based on the above
- if the query runs, save a new cached file (as an RDS) and delete the old one if it exists

Files are cached in `rappdirs::user_cache_dir("arcticreport")`

I modeled my approach based on what the `getlandsat` package does. We may want to consider whether users are warned that data will be cached. `getlandsat` just has a section of their readme explaining that caching happens, and no messages that I can see, so perhaps that is sufficient here. I think that it is, since this is a package primarily meant for internal use.

@mbjones if you have any thoughts let me know. These changes are in `develop`

**Comment by mbjones** [comment]
Sounds fine to me, given that we typically only run this ~quarterly, so refreshing the catch can be configured so that you reuse one data dump for any given report. Eventually it would be nice to make the underlying version chain traversal more efficient, but not strictly required for this application.

**Comment by jeanetteclark** [comment]
This is implemented in develop and seems to be working pretty well, so I'm going to close this issue
