### ISSUE TITLE
make cumulative size growth chart

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/arcticreport#11]
should look like this, need it quarterly

<img width="724" alt="Screen Shot 2023-11-09 at 1 03 31 PM" src="https://github.com/NCEAS/arcticreport/assets/24237074/d1b8367a-1fe4-4050-83a1-9ac82d8e4300">

**Comment by mbjones** [comment]
The code for this is here, which I manually tweak each time I want to run it.

https://github.nceas.ucsb.edu/KNB/arctic-data/blob/master/reporting/R/create-repo-size-projected-plot.R

**Comment by mbjones** [comment]
@jeanetteclark @justin Partial implementation of `plot_cumulative_volume()` added in sha b28ec2f Still remaining to do:

- [x] add parameter for `from` and `to` for `plot_cumulative_volume()` function
- [x] refactor `plot_cumulative_volume()` to use package styling more effectively
- [x] refactor to annotate the launch date consistently with the other plot functions

Here's an example plot made from the package:

![image](https://github.com/user-attachments/assets/82da3cde-ae64-45a6-9763-57a672f27292)

**Comment by mbjones** [comment]
Also, I found an issue where a bunch (500ish) rows had mostly missing values in the `objects` data frame, which caused an error when converting `dateUploaded` to a date object.  For now I just filtered them out on https://github.com/NCEAS/arcticreport/blob/cedd9f38f81a5c9c1ac1cecd95ad06fc23ab6fc4/R/plot_cumulative_volume.R#L17, but we should really dive in and find out where these rows originate and why the fields are missing:

- [ ] Determine why fields are missing from a bunch of rows and fix the issue
