### ISSUE TITLE
simplify process for getting file counts

### ISSUE THREAD

**Issue by mbjones** [NCEAS/arcticreport#14]
The current report arcticreport.Rmd file instructs the user to ssh to datateam, run a couple of complex commands, bring the data back to the running R session with specific names, and then runs some R code to transform that into a usable data frame that contains a list of the package identifiers, date uploaded, and sizes of the datasets stored on the filesystem.  It would be helpful to simplify this significantly.

**Comment by mbjones** [comment]
I added a potential solution to this in the new function `filesys_objects()` which parallels the `query_objects()` function. This is checked in sha b28ec2f in branch [`feature-11-volume-plot`](https://github.com/NCEAS/arcticreport/commits/feature-11-volume-plot/), and works by running a bash command on the `datateam` server that gathers the information using `stat` and `getfattr`. It returns a data frame that looks like this:

<img width="553" alt="image" src="https://github.com/user-attachments/assets/821b1061-6122-4544-b472-d8340d851ca7">

The column `size` is the total recursive size of the directory in bytes, and the column `rentries` is the total recursive count of the number of objects in the directory tree. These can be used to correct counts and volumes from Metacat.

**Comment by mbjones** [comment]
@justinkadi @jeanetteclark this table now has the recursive count data we would need to correct our object count stats and graph. Because of the way it is merged in before the objects table is grouped and summarized, this will require a bit of a logical restructure of the `count_data_objects()` function. Let's discuss how to best do this please.

**Comment by jeanetteclark** [comment]
done. got around the grouping by just doing some filtering within the function and calculating the number of metacat objects and number of file sys objects separately, and then returning the sum of those
